# Generated by Django 5.0.3 on 2024-04-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('valordadoação', models.CharField(max_length=40)),
                ('mensagemopcional', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('sobrenome', models.IntegerField()),
                ('Comogostaiadeserchamado', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('datadenascimento', models.CharField(max_length=8)),
                ('genero', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
            ],
        ),
    ]
