# Generated by Django 5.0.4 on 2024-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagemopcional', models.TextField()),
                ('celular', models.CharField(max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('mensagemopcional', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('valor_doacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('contador_doacoes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('rg', models.IntegerField()),
                ('orgExp', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('estado', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('sobrenome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('concordou_termos_voluntariado', models.BooleanField()),
                ('concordou_termos_imagem', models.BooleanField()),
            ],
        ),
    ]
