# Generated by Django 5.0.4 on 2024-05-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='rg',
            field=models.IntegerField(max_length=10),
        ),
    ]
